apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-operator
  namespace: skynet-operator
  labels:
    app.kubernetes.io/name: skynet
    app.kubernetes.io/component: skynet-operator
    app.kubernetes.io/managed-by: skynet-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: skynet
      app.kubernetes.io/component: skynet-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skynet
        app.kubernetes.io/component: skynet-operator
        app.kubernetes.io/managed-by: skynet-operator
    spec:
      serviceAccountName: skynet-operator
      containers:
        - name: skynet-operator
          image: quay.io/aswinsuryan/skynet:skynet-operator-latest
          imagePullPolicy: Always
          env:
            - name: RELATED_IMAGE_BROKER
              value: quay.io/aswinsuryan/skynet:skynet-broker-latest
            - name: RELATED_IMAGE_AGENT
              value: quay.io/aswinsuryan/skynet:skynet-agent-latest
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
