ARG BASE_BRANCH=devel
ARG FEDORA_VERSION=42
ARG SOURCE=/go/src/github.com/openshift/mcn

FROM --platform=${BUILDPLATFORM} golang:1.25 AS builder
ARG SOURCE
ARG TARGETPLATFORM

WORKDIR ${SOURCE}
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=linux GOARCH=$(echo ${TARGETPLATFORM} | cut -d/ -f2) \
    CGO_ENABLED=0 go build -o /output/mcn-broker ./cmd/broker

FROM --platform=${BUILDPLATFORM} fedora:${FEDORA_VERSION} AS base
ARG FEDORA_VERSION
ARG TARGETPLATFORM

COPY package/dnf_install /

RUN /dnf_install -a ${TARGETPLATFORM} -v ${FEDORA_VERSION} -r /output/broker \
    glibc bash glibc-minimal-langpack coreutils-single

FROM scratch
ARG TARGETPLATFORM

WORKDIR /

COPY --from=base /output/broker /
COPY --from=builder /output/mcn-broker /usr/local/bin/mcn-broker

ENTRYPOINT ["/usr/local/bin/mcn-broker"]
